# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_model_analysis/proto/wrappers.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.tensorflow_model_analysis/proto/wrappers.proto\x12\x19tensorflow_model_analysis\x1a\x1egoogle/protobuf/wrappers.proto\"\xb8\x03\n\tMyMessage\x12/\n\tmy_double\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12-\n\x08my_float\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12-\n\x08my_int64\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12/\n\tmy_uint64\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12-\n\x08my_int32\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\tmy_uint32\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12+\n\x07my_bool\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12/\n\tmy_string\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x08my_bytes\x18\t \x01(\x0b\x32\x1b.google.protobuf.BytesValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensorflow_model_analysis.proto.wrappers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MYMESSAGE']._serialized_start=110
  _globals['_MYMESSAGE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
